### PR TITLE
Feature/add memcached

### PR DESCRIPTION
**Pull request by jghyllebert**

### CODE REVIEW

**Comment by jghyllebert** [comment]
rebuild

**Comment by jwnwilson** [comment]
👍 Looks good!

**Comment by jghyllebert** [comment]
rebuild

**Comment by jghyllebert** [comment]
rebuild

**Comment by jghyllebert** [comment]
rebuild

**Comment by jghyllebert** [comment]
rebuild

**Comment by jghyllebert** [comment]
rebuild

**Comment by jghyllebert** [comment]
rebuild

**Pull request merged**
